### PR TITLE
Tracker Module Finalized

### PR DESCRIPTION
**Pull request by Nisar-Hassan**

### CODE REVIEW

**Comment by aa7985** [comment]
great

**Comment by Nisar-Hassan** [comment]
Lolz

**Comment by aa7985** [comment]
tu hai hi farig admi
eid waly din b chain nai hai tujy
rat ko mail karta tu kuch samj mn b ata
ab ignor karny k ilaawa koi option nahi hai

**Comment by Nisar-Hassan** [comment]
Kaam kasiaon ka hum kya karen mil milla ky yahi bacha karny ko

**Comment by aa7985** [comment]
hehe 😂 👍🏻

**Pull request merged**
